"""Add date_uploaded to PerformanceSummary

Revision ID: 0a30241b7d08
Revises: 59635bf6de5e
Create Date: 2025-10-10 20:47:32.579038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a30241b7d08'
down_revision = '59635bf6de5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('performance_summary', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_uploaded', sa.DateTime(), nullable=True))
        batch_op.alter_column('ebills',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('paydirect',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.drop_column('timestamp')

    with op.batch_alter_table('performance_target', schema=None) as batch_op:
        batch_op.drop_column('month')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('performance_target', schema=None) as batch_op:
        batch_op.add_column(sa.Column('month', sa.VARCHAR(length=20), nullable=True))

    with op.batch_alter_table('performance_summary', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DATETIME(), nullable=True))
        batch_op.alter_column('paydirect',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('ebills',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.drop_column('date_uploaded')

    # ### end Alembic commands ###
