"""Add role and target relationships

Revision ID: 0e34b0d1df67
Revises: cbd2c9b1351e
Create Date: 2025-10-22 23:48:56.603242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e34b0d1df67'
down_revision = 'cbd2c9b1351e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('performance_summary', schema=None) as batch_op:
        batch_op.alter_column('ebills',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('paydirect',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Float(),
               existing_nullable=True)

    with op.batch_alter_table('performance_target', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    with op.batch_alter_table('performance_target', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    with op.batch_alter_table('performance_summary', schema=None) as batch_op:
        batch_op.alter_column('paydirect',
               existing_type=sa.Float(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('ebills',
               existing_type=sa.Float(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###
