"""Add TaxEntry model

Revision ID: 4aeb331b405a
Revises: f282b192c51f
Create Date: 2025-10-11 14:33:02.642920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4aeb331b405a'
down_revision = 'f282b192c51f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tax_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tax_item', sa.String(length=100), nullable=True),
    sa.Column('subhead', sa.String(length=100), nullable=True),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('date_uploaded', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['uploaded_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tax_entry')
    # ### end Alembic commands ###
