"""Remove month from PerformanceTarget

Revision ID: 59635bf6de5e
Revises: 81a2e86de2b5
Create Date: 2025-10-10 20:38:28.480807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59635bf6de5e'
down_revision = '81a2e86de2b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('performance_summary', schema=None) as batch_op:
        batch_op.alter_column('ebills',
               existing_type=sa.FLOAT(),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('paydirect',
               existing_type=sa.FLOAT(),
               type_=sa.String(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('performance_summary', schema=None) as batch_op:
        batch_op.alter_column('paydirect',
               existing_type=sa.String(length=100),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('ebills',
               existing_type=sa.String(length=100),
               type_=sa.FLOAT(),
               existing_nullable=True)

    # ### end Alembic commands ###
