"""add user_id to PerformanceSummary

Revision ID: 6797af96e186
Revises: 7b57989a2e10
Create Date: 2025-10-19 10:50:45.539655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6797af96e186'
down_revision = '7b57989a2e10'
branch_labels = None
depends_on = None

def upgrade():
    with op.batch_alter_table('performance_summary', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            'fk_performance_summary_user_id',  # 👈 Give it a name
            'user',
            ['user_id'],
            ['id']
        )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('performance_summary', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
