"""Add payment verification fields to TaxEntry

Revision ID: 7b57989a2e10
Revises: 4aeb331b405a
Create Date: 2025-10-12 09:41:49.515339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b57989a2e10'
down_revision = '4aeb331b405a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('upload_log')
    with op.batch_alter_table('performance_summary', schema=None) as batch_op:
        # batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('sheet_name')
        batch_op.drop_column('remita_verified')
        batch_op.drop_column('interswitch_verified')
        batch_op.drop_column('uploaded_by')

    with op.batch_alter_table('tax_entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rrr', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('paydirect_ref', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('rrr_verified', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('paydirect_verified', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('rrr_amount', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('paydirect_amount', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tax_entry', schema=None) as batch_op:
        batch_op.drop_column('paydirect_amount')
        batch_op.drop_column('rrr_amount')
        batch_op.drop_column('paydirect_verified')
        batch_op.drop_column('rrr_verified')
        batch_op.drop_column('paydirect_ref')
        batch_op.drop_column('rrr')

    with op.batch_alter_table('performance_summary', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uploaded_by', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('interswitch_verified', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('remita_verified', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('sheet_name', sa.VARCHAR(length=100), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['uploaded_by'], ['id'])

    op.create_table('upload_log',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('date_uploaded', sa.DATETIME(), nullable=True),
    sa.Column('filename', sa.VARCHAR(length=255), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
