"""Add PerformanceTarget model

Revision ID: 81a2e86de2b5
Revises: 9924b893f9aa
Create Date: 2025-10-10 17:48:11.580386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81a2e86de2b5'
down_revision = '9924b893f9aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('performance_target',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('month', sa.String(length=20), nullable=True),
    sa.Column('target_amount', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('performance_target')
    # ### end Alembic commands ###
