"""Add PerformanceSummary and UploadLog

Revision ID: 90c15e3c4b4d
Revises: 90b0f1fd6228
Create Date: 2025-10-10 11:02:30.419626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90c15e3c4b4d'
down_revision = '90b0f1fd6228'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('performance_summary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sheet_name', sa.String(length=100), nullable=True),
    sa.Column('ato_name', sa.String(length=100), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=True),
    sa.Column('ebills', sa.Float(), nullable=True),
    sa.Column('paydirect', sa.Float(), nullable=True),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['uploaded_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('upload_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('upload_log')
    op.drop_table('performance_summary')
    # ### end Alembic commands ###
