"""Add Performance Table

Revision ID: 9924b893f9aa
Revises: 1abc22a6ba1a
Create Date: 2025-10-10 17:10:14.311740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9924b893f9aa'
down_revision = '1abc22a6ba1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('performance_summary', schema=None) as batch_op:
        batch_op.add_column(sa.Column('remita_verified', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('interswitch_verified', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('performance_summary', schema=None) as batch_op:
        batch_op.drop_column('interswitch_verified')
        batch_op.drop_column('remita_verified')

    # ### end Alembic commands ###
