"""Add month and year to TaxEntry

Revision ID: ebe9f1465820
Revises: 0e34b0d1df67
Create Date: 2025-11-03 10:42:52.265527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebe9f1465820'
down_revision = '0e34b0d1df67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
#    op.create_table('monthly_league_snapshot',
#    sa.Column('id', sa.Integer(), nullable=False),
#    sa.Column('month', sa.Integer(), nullable=True),
#    sa.Column('year', sa.Integer(), nullable=True),
#    sa.Column('data', sa.JSON(), nullable=True),
#    sa.Column('created_at', sa.DateTime(), nullable=True),
#    sa.PrimaryKeyConstraint('id')
#    )
    with op.batch_alter_table('performance_summary', schema=None) as batch_op:
        batch_op.alter_column('ebills',
               existing_type=sa.FLOAT(),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('paydirect',
               existing_type=sa.FLOAT(),
               type_=sa.String(length=50),
               existing_nullable=True)

    with op.batch_alter_table('performance_target', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    with op.batch_alter_table('tax_entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('month', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year', sa.Integer(), nullable=True))
        op.execute("CREATE UNIQUE INDEX IF NOT EXISTS uq_tax_entry_rrr ON tax_entry(rrr) WHERE rrr IS NOT NULL")
        op.execute("CREATE UNIQUE INDEX IF NOT EXISTS uq_tax_entry_paydirect_ref ON tax_entry(paydirect_ref) WHERE paydirect_ref IS NOT NULL")


    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), nullable=True))

    with op.batch_alter_table('tax_entry', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('year')
        batch_op.drop_column('month')

    with op.batch_alter_table('performance_target', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=True))

    with op.batch_alter_table('performance_summary', schema=None) as batch_op:
        batch_op.alter_column('paydirect',
               existing_type=sa.String(length=50),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('ebills',
               existing_type=sa.String(length=50),
               type_=sa.FLOAT(),
               existing_nullable=True)

    op.drop_table('monthly_league_snapshot')
    # ### end Alembic commands ###
