"""Rename timestamp to date_uploaded in UploadLog

Revision ID: f282b192c51f
Revises: 0a30241b7d08
Create Date: 2025-10-11 06:42:25.420106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f282b192c51f'
down_revision = '0a30241b7d08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('upload_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_uploaded', sa.DateTime(), nullable=True))
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('upload_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DATETIME(), nullable=True))
        batch_op.drop_column('date_uploaded')

    # ### end Alembic commands ###
